version: '3.5'

services:
  bookmarker-web:
    image: nginx:latest
    container_name: bookmarker-web
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "80:80"
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html

  bookmarker-app:
    build: ./docker/local/php-fpm
    container_name: bookmarker-app
    volumes:
      - ./web:/var/www/html

  bookmarker-mysql:
#    image: mysql:latest
    image: mysql:5.7
    restart: always
    container_name: bookmarker-mysql
    environment:
      MYSQL_DATABASE: bookmarker_db
      MYSQL_USER: bookmarker_user
      MYSQL_PASSWORD: bookmarker_user123
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/local/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - ./db-data:/var/lib/mysql
      - ./docker/local/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  bookmarker-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bookmarker-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=bookmarker-mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - bookmarker-mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
